set(_CATKIN_CURRENT_PACKAGE "rosboost_cfg")
set(rosboost_cfg_VERSION "1.14.4")
set(rosboost_cfg_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosboost_cfg_PACKAGE_FORMAT "1")
set(rosboost_cfg_BUILD_DEPENDS )
set(rosboost_cfg_BUILD_EXPORT_DEPENDS )
set(rosboost_cfg_BUILDTOOL_DEPENDS "catkin")
set(rosboost_cfg_BUILDTOOL_EXPORT_DEPENDS )
set(rosboost_cfg_EXEC_DEPENDS )
set(rosboost_cfg_RUN_DEPENDS )
set(rosboost_cfg_TEST_DEPENDS )
set(rosboost_cfg_DOC_DEPENDS )
set(rosboost_cfg_URL_WEBSITE "http://ros.org/wiki/rosboost_cfg")
set(rosboost_cfg_URL_BUGTRACKER "")
set(rosboost_cfg_URL_REPOSITORY "")
set(rosboost_cfg_DEPRECATED "")