set(_CATKIN_CURRENT_PACKAGE "rosmaster")
set(rosmaster_VERSION "1.12.14")
set(rosmaster_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosmaster_PACKAGE_FORMAT "1")
set(rosmaster_BUILD_DEPENDS )
set(rosmaster_BUILD_EXPORT_DEPENDS "rosgraph" "python-defusedxml")
set(rosmaster_BUILDTOOL_DEPENDS "catkin")
set(rosmaster_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(rosmaster_BUILDTOOL_EXPORT_DEPENDS )
set(rosmaster_EXEC_DEPENDS "rosgraph" "python-defusedxml")
set(rosmaster_RUN_DEPENDS "rosgraph" "python-defusedxml")
set(rosmaster_TEST_DEPENDS )
set(rosmaster_DOC_DEPENDS )
set(rosmaster_URL_WEBSITE "http://ros.org/wiki/rosmaster")
set(rosmaster_URL_BUGTRACKER "")
set(rosmaster_URL_REPOSITORY "")
set(rosmaster_DEPRECATED "")