set(_CATKIN_CURRENT_PACKAGE "roslz4")
set(roslz4_VERSION "1.12.14")
set(roslz4_MAINTAINER "Ben Charrow <bcharrow@seas.upenn.edu>")
set(roslz4_PACKAGE_FORMAT "1")
set(roslz4_BUILD_DEPENDS "lz4")
set(roslz4_BUILD_EXPORT_DEPENDS "lz4")
set(roslz4_BUILDTOOL_DEPENDS "catkin")
set(roslz4_BUILDTOOL_EXPORT_DEPENDS )
set(roslz4_EXEC_DEPENDS "lz4")
set(roslz4_RUN_DEPENDS "lz4")
set(roslz4_TEST_DEPENDS "rosunit")
set(roslz4_DOC_DEPENDS )
set(roslz4_URL_WEBSITE "")
set(roslz4_URL_BUGTRACKER "")
set(roslz4_URL_REPOSITORY "")
set(roslz4_DEPRECATED "")