set(rosclean_SETUP_PY_VERSION "1.14.4")
set(rosclean_SETUP_PY_SCRIPTS "scripts/rosclean")
set(rosclean_SETUP_PY_PACKAGES "rosclean")
set(rosclean_SETUP_PY_PACKAGE_DIRS "src/rosclean")
set(rosclean_SETUP_PY_MODULES "")
set(rosclean_SETUP_PY_MODULE_DIRS "")