set(_CATKIN_CURRENT_PACKAGE "rospack")
set(rospack_VERSION "2.4.4")
set(rospack_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rospack_PACKAGE_FORMAT "1")
set(rospack_BUILD_DEPENDS "boost" "cmake_modules" "gtest" "pkg-config" "python" "tinyxml")
set(rospack_BUILD_EXPORT_DEPENDS "boost" "pkg-config" "python" "python-catkin-pkg" "python-rosdep" "tinyxml")
set(rospack_BUILDTOOL_DEPENDS "catkin")
set(rospack_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(rospack_BUILDTOOL_EXPORT_DEPENDS )
set(rospack_EXEC_DEPENDS "boost" "pkg-config" "python" "python-catkin-pkg" "python-rosdep" "tinyxml")
set(rospack_RUN_DEPENDS "boost" "pkg-config" "python" "python-catkin-pkg" "python-rosdep" "tinyxml")
set(rospack_TEST_DEPENDS "python-coverage")
set(rospack_DOC_DEPENDS )
set(rospack_URL_WEBSITE "http://wiki.ros.org/rospack")
set(rospack_URL_BUGTRACKER "https://github.com/ros/rospack/issues")
set(rospack_URL_REPOSITORY "https://github.com/ros/rospack")
set(rospack_DEPRECATED "")