controller_list:
  - name: fake_Beo_Arm_M4_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      []
initial:  # Define initial robot poses.
  - group: Beo_Arm_M4
    pose: Fold